---
- name: Start playbook
  hosts: all  #DB
  become: true
  become_method: sudo
  user: centos
  ignore_errors: true          #Dont stop if there are errors
  tasks:

  - name: Start r1soft
    when: (ansible_distribution == “CentOS” and ansible_distribution_major_version == “7")
    systemd:
      name: sbm-agent
      state: started
    ignore_errors: true


  - name: Start Filebeat
    systemd:
      name: filebeat
      state: started
    ignore_errors: true

  - name: Start NRPE
    systemd:
      name: nrpe
      state: started
    ignore_errors: true

  - name: Start Mariadb
    systemd:
      name: mariadb
      state: started
    ignore_errors: true